
Include:
  - Datasources
  - Resolutions/High
  - Background/Skybox

Animation:
  Speed: 200
  Crop: [1000, 83500]

View:
  Background: [0., 0., 0.]
  OrientationAxesVisibility: False

WaveformToVolume:
  Size: 120
  RadialScale: 4
  InvertRotationDirection: True
  EllMax: 2
  ActivationOffset: 10
  ActivationWidth: 10
  DeactivationWidth: 10
  SpatialResolution: 300
  KeepEveryNthTimestep: 50
  StoreIndividualModes: False
  Polarizations: ["Plus"]

VolumeRepresentation:
  Representation: Volume
  VolumeRenderingMode: GPU Based
  Shade: True
  ScalarOpacityUnitDistance: 5.
  ColorBy: Plus strain

TransferFunctions:
  - Field: Plus strain
    TransferFunction:
      Peaks:
        NumPeaks: 6
        FirstPeak:
          Position: 0.006
          Opacity: 0.3
        LastPeak:
          Position: 0.02
          Opacity: 0.4
        Logarithmic: True
        Colormap:
          Exported: [-0.9749279022216797, 0.49019607843137253, 0.0, 0.8431372549019608, -0.9081104397773743, 1.0, 0.00392156862745098, 0.9019607843137255, -0.829144299030304, 0.9882352941176471, 0.0, 0.3137254901960784, -0.7501781582832336, 1.0, 0.0, 0.21568627450980393, -0.4707595705986023, 1.0, 0.4666666666666667, 0.0, 0.25815850496292114, 1.0, 0.7137254901960784, 0.21568627450980393, 0.5922459363937378, 1.0, 0.8392156862745098, 0.4588235294117647, 0.9749279022216797, 1.0, 0.9019607843137255, 0.6509803921568628]
          ColorSpace: Lab
  - Field: Age
    TransferFunction:
      Custom:
        Points:
          - Position: 0
            Opacity: 0
          - Position: 0
            Opacity: 0.6
          - Position: 200
            Opacity: 0
          - Position: 300
            Opacity: 0
        Colormap:
          Name: Grayscale
          Invert: True

# NR and EOB data is aligned such that their mergers coincide. The transition
# from the EOB to the NR trajectory happens between segments 4 and 5.

Trajectories:
  - Name: PrimaryObject
    Objects:
      - Sphere:
          Radius: 2
          ThetaResolution: 100
          PhiResolution: 100
        Visibility:
          Start: 0
          End: 78000
        Representation:
          AmbientColor: [0., 0., 0.]
          DiffuseColor: [0., 0., 0.]
          Specular: 0.2
          SpecularPower: 10
          SpecularColor: [1., 1., 1.]
  - Name: SecondaryObject
    Objects:
      - Sphere:
          Radius: 0.2
          ThetaResolution: 100
          PhiResolution: 100
        Visibility:
          Start: 0
          End: 78000
        Representation:
          AmbientColor: [0., 0., 0.]
          DiffuseColor: [0., 0., 0.]
          Specular: 0.2
          SpecularPower: 10
          SpecularColor: [1., 1., 1.]
    Tail:
      LineWidth: 1.5
      ColorBy: Age
      Visibility:
        Start: 0
        End: 78000
  - Name: SecondaryHorizonTail
    TimeShift:
      PreShift: 76041
    Tail:
      LineWidth: 1.5
      ColorBy: Age
      Visibility:
        Start: 78000
        End: 82662
        FadeOut:
          TimeMode: Scene
          Time: 30

Horizons:
  - Name: PrimaryHorizon
    TimeShift:
      PreShift: 76041
    Visibility:
      Start: 78000
      End: 82662
    Representation:
      Representation: Surface
      AmbientColor: [0., 0., 0.]
      DiffuseColor: [0., 0., 0.]
      Specular: 0.2
      SpecularPower: 10
      SpecularColor: [1., 1., 1.]
  - Name: SecondaryHorizon
    TimeShift:
      PreShift: 76041
    Visibility:
      Start: 78000
      End: 82662
    Representation:
      Representation: Surface
      AmbientColor: [0., 0., 0.]
      DiffuseColor: [0., 0., 0.]
      Specular: 0.2
      SpecularPower: 10
      SpecularColor: [1., 1., 1.]
  - Name: CommonHorizon
    TimeShift:
      PreShift: 76041
    Visibility:
      Start: 82662
      End: 85000
    Representation:
      Representation: Surface
      AmbientColor: [0., 0., 0.]
      DiffuseColor: [0., 0., 0.]
      Specular: 0.2
      SpecularPower: 10
      SpecularColor: [1., 1., 1.]

CameraShots:
  - Position: [0., -260., 50.]
    ViewUp: [0., 0., 1.]
    FocalPoint: [0., 0., 0.]
    ViewAngle: 60.
